defaults:
  - _base              
  - _self_
dataset: sst2           
model:
  name: roberta-base    
method: prompt_v1      
method_cfg:             
  num_virtual_tokens: 10       
  init_text: null
device: cuda:0